### ISSUE TITLE
Not loading up

### ISSUE THREAD

**Issue by jelee1988** [ardeus-ua/ha-tasmota#2]
2018-07-16 16:03:35 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.light.tasm. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/loader.py", line 86, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/light/tasm.py", line 11, in <module>
    from homeassistant.components.light import (
ImportError: cannot import name 'SUPPORT_RGB_COLOR'
2018-07-16 16:03:35 ERROR (MainThread) [homeassistant.loader] Unable to find component light.tasm

**Comment by ardeus-ua** [comment]
I have gave up on rework of the plugin once HA switched MQTT light to HSB and configured it like a regular mqtt light based on the instructions from arendst
